plugins { id 'com.android.application' }

def releaseKeystore = System.getenv('ANDROID_KEYSTORE_PATH')

android {
    namespace 'com.longkaca.dpc'
    compileSdk 34

    defaultConfig {
        applicationId 'com.longkaca.dpc'
        minSdk 26
        targetSdk 34
        versionCode 20
        versionName '2.9-cloudflare-apn-off'
    }

    signingConfigs {
        release {
            if (releaseKeystore) {
                storeFile file(releaseKeystore)
                storePassword System.getenv('ANDROID_KEYSTORE_PASSWORD')
                keyAlias System.getenv('ANDROID_KEY_ALIAS')
                keyPassword System.getenv('ANDROID_KEY_PASSWORD')
            }
        }
    }
    buildTypes {
        release {
            if (releaseKeystore) signingConfig signingConfigs.release
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'
}
