plugins { id 'com.android.application' }

android {
    namespace 'com.longkaca.dpc'
    compileSdk 34

    defaultConfig {
        applicationId 'com.longkaca.dpc'
        minSdk 26
        targetSdk 34
        versionCode 13
        versionName '2.2-split-fix-email-list-apn'
    }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'
}
