plugins { id 'com.android.application' }

android {
    namespace 'com.longkaca.dpc'
    compileSdk 34

    defaultConfig {
        applicationId 'com.longkaca.dpc'
        minSdk 26
        targetSdk 34
        versionCode 4
        versionName '1.3-phone-test'
    }
}

dependencies {
    implementation 'com.google.zxing:core:3.5.3'
}
